//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Block
{
	public virtual int board_x
	{
		get;
		set;
	}

	public virtual Polyomino piece
	{
		get;
		set;
	}

	public virtual int board_y
	{
		get;
		set;
	}

	public virtual int draw_y
	{
		get;
		set;
	}

	public virtual int draw_x
	{
		get;
		set;
	}

	public virtual void Draw()
	{
		throw new System.NotImplementedException();
	}

	public virtual void UpdateLocation(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetLocation(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CanMove(int x, y int)
	{
		throw new System.NotImplementedException();
	}

}

