//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class CanChangeLocalVisitor
{
	public virtual Board board
	{
		get;
		set;
	}

	public virtual bool CanMoveOnBoardCall(Polyomino poly, state int, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool IPiece(IPiece piece, object int state, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual void CanMoveOnBoardVisitor(Board board)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool OPiece(OPiece piece, object int state, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool LPiece(LPiece piece, object int state, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool SPiece(SPiece piece, object int state, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool ZPiece(ZPiece piece, object int state, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool JPiece(JPiece piece, object int state, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool Block(Block block, object int x, object int y)
	{
		throw new System.NotImplementedException();
	}

}

