//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MoveOnBoardVisitor
{
	public virtual Board board
	{
		get;
		set;
	}

	public virtual CanChangeLocalVisitor canChange
	{
		get;
		set;
	}

	public virtual FinalizeOnBoardVisitor finalize
	{
		get;
		set;
	}

	public virtual void MoveOnBoardCall(Polyomino poly)
	{
		throw new System.NotImplementedException();
	}

	public virtual void IPiece(IPiece piece, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

	public MoveOnBoardVisitor(Board board, CanChangeLocalVisitor change, FinalizeOnBoardVisitor final)
	{
	}

	public virtual void OPiece(OPiece piece, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

	public virtual void LPiece(LPiece piece, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

	public virtual void SPiece(SPiece piece, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ZPiece(ZPiece piece, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

	public virtual void JPiece(JPiece piece, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Block(Block block, int dx, int dy)
	{
		throw new System.NotImplementedException();
	}

}

