//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Drawing;

using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Polyomino
{
    int _state;
    Boolean _whole;
    Block[] block;
    //private ghostBlock[] gblock;
     ConsoleColor _color;


	public virtual int state
	{
		get { return this._state; }
		set { this._state = value; }
	}

	public virtual Color color
	{
		get {return this._color; }
		set { this._color = value; }
	}

	public virtual bool whole
	{
		get { return _whole };
		set { this._whole = value };
	}

	public virtual Block[] blocks
	{
		get;
		set;
	}

	public virtual Block[] ghostBlocks
	{
		get;
		set;
	}

	public virtual IEnumerable<Block> Block
	{
		get;
		set;
	}

	public virtual void Draw()
	{
		throw new System.NotImplementedException();
	}

	public abstract void RotateLeft();

	public abstract void RotateRight();

	public virtual bool MoveContinous(int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MoveOnBoard(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CanMoveOnBoard(x int, y int)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FinalizeOnBoard(Board board)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DropRow(Board board)
	{
		throw new System.NotImplementedException();
	}


    static void Main(string[] args)
    {
        Console.WriteLine("Hello World");
        Console.ReadLine();
    }




}

