//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Polyomino
{
	public virtual int state
	{
		get;
		set;
	}

	public virtual Color color
	{
		get;
		set;
	}

	public virtual bool whole
	{
		get;
		set;
	}

	public virtual Block[] blocks
	{
		get;
		set;
	}

	public virtual Block[] ghostBlocks
	{
		get;
		set;
	}

	public virtual IEnumerable<Block> Block
	{
		get;
		set;
	}

	public virtual void Draw()
	{
		throw new System.NotImplementedException();
	}

	public abstract void RotateLeft();

	public abstract void RotateRight();

	public virtual bool MoveContinous(int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool MoveOnBoard(int x, int y)
	{
		throw new System.NotImplementedException();
	}

	public virtual bool CanMoveOnBoard(x int, y int)
	{
		throw new System.NotImplementedException();
	}

	public virtual void FinalizeOnBoard(Board board)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DropRow(Board board)
	{
		throw new System.NotImplementedException();
	}

}

